### PR TITLE
Add interactive compilation mode

### PR DESCRIPTION
**Pull request by dmh43**
It's been convenient for me to have a mode where I can see the JS compilation results without having to manually compile the buffer. I figured I would share it. Comments and criticisms as well as suggestions are very welcome!

### CODE REVIEW

**Comment by syohex** [comment]
Is it enough to use `coffee-cos-mode` which compiles buffer at saving buffer for your purpose ?

And what does **interactive** mean in that mode? Emacs usually uses **interactive** as **conversational**. However I suppose that `coffee-icomp-mode` is not interactive.

**Comment by dmh43** [comment]
Ah yes, that's a good point. I am using 'interactive' incorrectly in the context of emacs.

This minor mode is kind of like the "Try coffeescript" feature on [http://coffeescript.org/](http://coffeescript.org/)

The benefit I have found of this minor mode is that you can see the effect of your changes on the fly. So as you change your coffeescript source, the compiled buffer immediately shows the changes. It is a subtle difference. I also understand if this doesn't fit your workflow. I have found that it has been convenient for me sometimes.

Furthermore, I will not be heartbroken if you decide that such a feature is unneeded :)

**Comment by syohex** [comment]
Thanks for PR. I have merge #349 which is based on your PR and some refactoring.

**Comment by dmh43** [comment]
👍 Thanks!

**Pull request closed without merging**
