### PR TITLE
invalidate block-comment start after ####

### LINKED ISSUE #362: valid-comment-start should be false after #{4,}
coffee-mode currently begins multiline comments after '####'

```coffeescript
#### Example
console.log "I'm not in a comment"
```

### PR DESCRIPTION
**Pull request by millerjs**
Closes #362.

### CODE REVIEW

**Comment by millerjs** [comment]
bump @defunkt 😁

**Comment by Wilfred** [comment]
cc @syohex would you mind merging this?

**Comment by millerjs** [comment]
bump @syohex 😁

**Comment by millerjs** [comment]
bump @syohex 🦄

**Comment by syohex** [comment]
Thanks for PR

**Pull request merged**
